name: my_point
description: My Point
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

# * Application Packages and Libraries
# * Flutter Packages overrides for conflict resolution
dependency_overrides:
  intl: ^0.18.1

dependencies:
  camera: ^0.11.1
  collection: ^1.18.0
  connectivity_plus: ^6.1.1
  crop_your_image: ^2.0.0
  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^4.0.1
  device_info_plus: ^11.2.0
  dio: ^5.1.1
  equatable: ^2.0.7
  file_picker: 10.2.0
  firebase_analytics: ^11.6.0
  firebase_core: 3.15.2
  firebase_crashlytics: ^4.3.10
  firebase_messaging: 15.2.10
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_contacts: ^1.1.9
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.13.10
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  fpdart: ^1.1.0
  freezed_annotation: ^2.2.0
  get_it: ^8.0.3
  go_router: ^14.2.3
  google_api_availability: ^5.0.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  injectable: ^2.1.1
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.5
  intl_utils: ^2.8.10
  introduction_screen: ^3.1.17
  js: ^0.7.2
  jwt_decode: ^0.3.1
  l: ^5.0.0
  like_button: ^2.0.5
  logger: ^2.6.0
  logging: ^1.2.0
  package_info_plus: ^8.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  photo_manager: 3.7.1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  pulsator: ^1.0.0+2
  record: ^5.1.2
  rxdart: ^0.28.0
  sentry_flutter: 9.5.0
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  stack_trace: ^1.11.1
  timeago: ^3.6.1
  upgrader: ^11.3.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  version: ^3.0.2
  video_player: ^2.9.5
  video_thumbnail: 0.5.6
  web_socket_channel: ^3.0.2

# * Packages that will not be in the release version of app
dev_dependencies:
  bloc_test: ^10.0.0

  # * Code Generators
  # Generating Files
  build_runner: ^2.4.6

  # * UI Testing
  # Generate Fake Data
  faker: ^2.0.0
  # Generating Asset Files
  flutter_gen_runner: ^5.1.0+1

  # * Linter and code organization
  # Linter
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  # Code Generation for Models and Union Types
  freezed: ^2.2.0
  # Injecting Dependencies
  injectable_generator: ^2.1.1
  # Generating Serialization of JSON
  json_serializable: ^6.5.4
  # Data Mocking
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/app_images/
    - assets/splash/
    - assets/fonts/

  fonts:
    - family: app_icons
      fonts:
        - asset: assets/fonts/app_icons.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

# * Localizations generating config
flutter_intl:
  enabled: true
  arb_dir: lib/src/core/localization/intl
  output_dir: lib/src/core/localization/generated
  class_name: S # This is the default class name for the generated delegate
  main_locale: ru # Specify your main locale
  translate_var: loc # This matches your context.loc usage

# * Flutter Icon Generator Configurations
flutter_icons:
  image_path: "assets/icons/stage.png"
  # Android Icon
  android: true
  adaptive_icon_background: "#1E1E1E"
  # iOS Icon
  ios: true
  remove_alpha_ios: true
