# # This file contains the fastlane.tools configuration
# # You can find the documentation at https://docs.fastlane.tools
# #
# # For a list of all available actions, check out
# #
# #     https://docs.fastlane.tools/actions
# #
# # For a list of all available plugins, check out
# #
# #     https://docs.fastlane.tools/plugins/available-plugins
# #

# # Uncomment the line if you want fastlane to automatically update itself
# # update_fastlane

# default_platform(:ios)

# platform :ios do
#   desc "Push a new release build to the App Store"
#   lane :release do
#     build_app(workspace: "Runner.xcworkspace", scheme: "production")
#     upload_to_app_store
#   end
# end


default_platform(:ios)

platform :ios do
  desc "Automates deployment to TestFlight in the Flutter project"
  lane :beta do
    sh("pod install")

    app_store_connect_api_key(
      key_id: ENV["APPLE_AUTH_KEY_ID"],
      issuer_id: ENV["APPLE_AUTH_KEY_ISSUER_ID"],
      key_filepath: "./fastlane/AuthKey.p8",
      duration: 1200,
      in_house: false
    )

    import_certificate(
      certificate_path: "./fastlane/DistributionCertificate.p12",
      certificate_password: ENV["DISTRIBUTION_CERTIFICATE_PASSWORD"],
      keychain_name: "login",
      keychain_password: "GreenKozMac"
    )

    get_provisioning_profile(
      output_path: "./fastlane/profiles",
      filename: "appstore.mobileprovision",
      provisioning_name: "kz.jet-join.app AppStore",
      ignore_profiles_with_different_name: true,
      app_identifier: "kz.jet-join.app"
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      targets: ["Runner"],
      path: "Runner.xcodeproj",
      code_sign_identity: "Yerkebulan Zhigerbayev",
      build_configurations: ['Release'],
      sdk: "iphoneos*",
      profile_name: "kz.jet-join.app AppStore"
    )

    Dir.chdir "../.." do
      sh(
        "flutter",
        "build",
        "ipa",
        "--no-codesign",
        "--flavor",
        "production"
      )
    end

    build_ios_app(
      workspace: "Runner.xcworkspace",
      configuration: "Release",
      scheme: "Runner",
      silent: true,
      clean: true,
      output_directory: "./fastlane/build",
      output_name: "app.ipa",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "kz.jet-join.app" => "kz.jet-join.app AppStore",
        }
      }
    )

    upload_to_testflight(
      ipa: "./fastlane/build/app.ipa",
      skip_submission: true,
      skip_waiting_for_build_processing: true,
    )
  end
end