/// Flutter icons AppIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
library;
// coverage:ignore-file
// ignore_for_file: type=lint

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons();

  static const _kFontFam = 'app_icons';
  static const String? _kFontPkg = null;

  IconData airplay = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData alert = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_down_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_down_left = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_down_right = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_down = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_left = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_left_circle = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_right_circle = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_right = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_up_circle = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_up_left = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_up = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_up_right = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData at_sign = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData attachment = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData back = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData box = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData calendar = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData camera_off = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData cart = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData camera = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData catalog = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chart_bar_horizontal = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chart_bar_vertical = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chart_line = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chart_pie = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chat = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData check = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevron_down = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevron_left = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevron_right = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevron_up = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevrons_down = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevrons_left = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevrons_right = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevrons_up = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData circle_filled = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData circle = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData clock = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData close_circle_filled = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData close_circle = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData close = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData copy = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData corner_down_left = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData corner_down_right = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData corner_left_down = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData corner_left_up = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData corner_right_down = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData corner_right_up = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData corner_up_left = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData corner_up_right = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData crop = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData delivery = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData diamond = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData dislike_filled = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData dislike = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData division = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData download = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData download_cloud = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData edit_2 = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData equality = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData erase = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData fall = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData fast_back = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData fast_forward = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData file_plus = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData file = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData film = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData filter = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData flame = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData folder_plus = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData folder = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData gallery = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData gift = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData globe = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData hash_sign = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData heart_filled = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData heart = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData help = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData home = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData info = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData invoice = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData language_square = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData like_filled = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData like = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData link = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData lock = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData mail = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData map_pin_filled = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData map_pin = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData map = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData maximize_arrows = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData maximize = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData menu = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData mic = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData minimize_arrows = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData minimize = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData minus = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData money = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData monitor = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData moon = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData more_circle = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData more = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData move = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData multiplication = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData music = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData navigator_current = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData navigator = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData next = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData notifications_off = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData notifications = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData pause_circle = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData pause = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData percent = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData phone = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData play_circle = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData play = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData plus_square = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData plus_minus = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData plus = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData printer = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData profile = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData protection_off = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData protection = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData pulse = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData referral = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData refresh = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData rise = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData rotate_left = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData rotate_right = IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData search = IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData send = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData setting_2 = IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData settings = IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData shopping_bag = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData shuffle = IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData sign_in = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData sign_out = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData smartphone = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData smile = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData square = IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData star_filled = IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData star = IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData sun = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData tablet = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData trash = IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData tv = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData unlock = IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData upload_cloud = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData upload = IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData user = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData video_off = IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData video = IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData views_off = IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData views = IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData voicrmail = IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData volume_0 = IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData volume_1 = IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData volume_2 = IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData volume_off = IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData watch = IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData wifi_off = IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData wifi = IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData write = IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData zoom_in = IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData zoom_out = IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
